#!/bin/sh
#### Creates ifcfg-tap$1 file and stores in /etc/sysconfig/network directory #######

if [ -z "$1" ] ; then
    echo "USAGE : $0 <path_to_networking> <number of the tap interface>"
    exit 1;
fi
if [ $2 -eq "0" ]; then
    echo "   (Note: tap0 cannot be configured)";
    exit 1;
fi 
if [ ! -d $1 ]; then
    echo "Error: $1 does not exist, exiting";
    exit 2;
fi

iface="$1/ifcfg-tap$2";

if [ -f $iface ]; then
    echo "$iface exists."
else
    echo -e "DEVICE=tap$2\nTUNNEL=Tap\nONBOOT=yes\nSTARTMODE=auto\nBRIDGE=br$2\nINTERFACETYPE=tap\nTUNNEL_LOCAL_IPADDR=0.0.0.0\nTUNNEL_SET_PERSISTENT=yes" \
    > $iface
fi
