#!/bin/sh
#### Creates ifcfg-br$1 file and stores in /etc/sysconfig/network directory #######


if [ -z "$1" ] ; then
    echo "USAGE : $0 <path_to_networking> <number of the bridge interface>"
    exit 1;
fi
if [ $2 = "0" ]; then
    echo "   (Note: br0 cannot be configured)";
    exit 1;
fi 
if [ ! -d $1 ]; then
    echo "Error: $1 does not exist, exiting";
    exit 2;
fi

iface="$1/ifcfg-br$2";

if [ -f $iface ]; then
    echo "$iface exists."
else
    echo "create $iface";
    echo -e "DEVICE=br$2\nTYPE=Bridge\nNM_CONTROLLED=no\nONBOOT=no\nSTARTMODE=auto\nDELAY=0\nBRIDGE=yes\nBRIDGE_PORTS='eth$2 tap$2'\nBRIDGE_FORWARDDELAY=0" \
    > $iface
fi
