#!/bin/sh
#### Creates ifcfg-eth$1 file and stores in /etc/sysconfig/network directory #######
if [ -z "$1" ] ; then
    echo "USAGE : $0 <path_to_networking> <number of the eth interface>"
    exit 1;
fi
if [ $2 = "0" ]; then
    echo "   (Note: eth0 cannot be configured)";
    exit 1;
fi 
if [ ! -d $1 ]; then
    echo "Error: $1 does not exist, exiting";
    exit 2;
fi

iface="$1/ifcfg-eth$2";

if [ -f $iface ]; then
    echo "$iface exists."
else
    echo -e "DEVICE=eth$2\nTYPE=Ethernet\nNM_CONTROLLED=no\nONBOOT=no\nNETMASK=255.255.255.0\nSTARTMODE=auto\nBridge=br$2" > $iface
fi
