#!/bin/sh
if [ $# -ne "2" ]; then
    echo "Usage: $0 Input_Port_number Output_Port_number"
    echo "Usage example for Flow13 $0 1 3"
    exit 1;
fi 

IN_PORT=$1
OUT_PORT=$2
FLOW_NAME=Flow$IN_PORT$OUT_PORT

#####################################################################
#####     No need to change anything from here on 		#####
#####################################################################
echo "rr(of_protocol)."
echo "InPortField1 = #ofp_field{field = in_port, value = <<$IN_PORT:32>>}."
echo "Match1 = #ofp_match{oxm_fields = [InPortField1]}."
echo "ActionOutput1 = #ofp_instruction_write_actions{"
echo "actions = [#ofp_action_set_queue{port ="
echo "$OUT_PORT,"
echo ""                             
echo "queue_id = 1},"
echo ""                             
echo "#ofp_action_output{port = $OUT_PORT}]}."
echo "$FLOW_NAME = #ofp_flow_mod{table_id = 0,"
echo ""                             
echo "priority = 1,"
echo ""                             
echo "command = add,"
echo ""                             
echo "match = Match1,"
echo ""                             
echo "instructions = [ActionOutput1]"
echo ""                             
echo "}."
echo "ofs_userspace:ofp_flow_mod(state, $FLOW_NAME)."
