#!/bin/sh
LINC_SCRIPT_DIR=/usr/local/src/linc/misc_tools

### Change the value of num_interfaces to correspond to the number required
if [ -z "$1" ] ; then
   echo "USAGE : $0 <num_interfaces>"
   exit
fi

num_interfaces=$1

### Interface numbering starts at 1, by default, and are sequential
start_if_num=01

#####################################################################
#####     No need to change anything from here on 		#####
#####################################################################

echo "Creating Bridges, Taps and add the same to physical interfaces ..."
echo "================================="
for ((i=start_if_num; i <= num_interfaces; i++))
do
	$LINC_SCRIPT_DIR/create_ifcfg_eth $i
	$LINC_SCRIPT_DIR/create_ifcfg_br $i
	$LINC_SCRIPT_DIR/create_ifcfg_tap $i
done
